import type { ProFormaResult } from "@papuc/core";

export interface CsvExportInput {
  address: string;
  price: number;
  beds?: number | null;
  baths?: number | null;
  sqft?: number | null;
  result: ProFormaResult;
}

const MONTH_NAMES = [
  "Jan",
  "Feb",
  "Mar",
  "Apr",
  "May",
  "Jun",
  "Jul",
  "Aug",
  "Sep",
  "Oct",
  "Nov",
  "Dec",
];

export function exportProFormaCsv(input: CsvExportInput): void {
  const csv = buildCsv(input);
  const filename = sanitizeFilename(`${input.address || "deal"}.csv`);
  const blob = new Blob([csv], { type: "text/csv;charset=utf-8" });
  const url = URL.createObjectURL(blob);
  const a = document.createElement("a");
  a.href = url;
  a.download = filename;
  document.body.appendChild(a);
  a.click();
  a.remove();
  setTimeout(() => URL.revokeObjectURL(url), 1000);
}

function buildCsv({
  address,
  price,
  beds,
  baths,
  sqft,
  result,
}: CsvExportInput): string {
  const lines: string[] = [];
  lines.push(`Address,${csvEscape(address)}`);
  lines.push(`Price,${price}`);
  lines.push(`Beds,${beds ?? ""}`);
  lines.push(`Baths,${baths ?? ""}`);
  lines.push(`Sqft,${sqft ?? ""}`);
  lines.push("");
  lines.push("Summary,Value");
  lines.push(`Initial Sunk Investment,${result.initialSunkInvestment.toFixed(2)}`);
  lines.push(`Annual Pre-Tax Profit,${result.annualPreTaxProfit.toFixed(2)}`);
  lines.push(`Annual After-Tax Profit,${result.annualPostTaxProfit.toFixed(2)}`);
  lines.push(`Cash-on-Cash,${(result.cashOnCashReturn * 100).toFixed(2)}%`);
  lines.push(`Payout Years,${result.payoutYears.toFixed(2)}`);
  lines.push(
    `5-Yr IRR,${result.irr5Yr !== null ? `${(result.irr5Yr * 100).toFixed(2)}%` : ""}`,
  );
  lines.push(`5-Yr Equity Multiple,${result.equityMultiple5Yr.toFixed(2)}`);
  lines.push(`Monthly PITIA,${result.pitiaMonthly.total.toFixed(2)}`);
  lines.push(`  - P&I,${result.pitiaMonthly.principalAndInterest.toFixed(2)}`);
  lines.push(`  - Taxes,${result.pitiaMonthly.taxes.toFixed(2)}`);
  lines.push(`  - Insurance,${result.pitiaMonthly.insurance.toFixed(2)}`);
  lines.push(`  - HOA,${result.pitiaMonthly.hoa.toFixed(2)}`);
  lines.push(`  - PMI,${result.pitiaMonthly.pmi.toFixed(2)}`);
  lines.push(`DSCR,${result.dscr.toFixed(3)}`);
  lines.push(`DSCR (lender 75% rent),${result.dscrLenderHaircut.toFixed(3)}`);
  lines.push("");
  lines.push("Month,Revenue,Variable,Contribution,Fixed,Pre-Tax Profit");
  for (let m = 0; m < 12; m++) {
    lines.push(
      [
        MONTH_NAMES[m],
        result.monthlyRevenue[m]!.toFixed(2),
        result.monthlyVariableCosts[m]!.toFixed(2),
        result.monthlyContributions[m]!.toFixed(2),
        result.monthlyFixedCosts[m]!.toFixed(2),
        result.monthlyPreTaxProfit[m]!.toFixed(2),
      ].join(","),
    );
  }
  lines.push("");
  lines.push("Generated by Papuc.");
  return lines.join("\n");
}

function csvEscape(s: string): string {
  if (/[",\n]/.test(s)) {
    return `"${s.replace(/"/g, '""')}"`;
  }
  return s;
}

function sanitizeFilename(name: string): string {
  return name.replace(/[^A-Za-z0-9._-]+/g, "_");
}
